language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install cwatm . # install package + test dependencies
script: pytest ./pytesting/test_cwatm3.py --html=report.html --settingsfile=./pytesting/test_py_catwm1.txt