language: python
python:
  - 3.7
os:
- linux  

addons:
  apt:
    packages:
    - libgdal-dev
  
before_install:
  - sudo apt-get install libgdal-dev
  - sudo apt-get install python3-gdal

install:
  - pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`
  - pip install -r requirements.txt

script:
  - python run_cwatm.py
  
after_script:
   - bash <(curl -s https://codecov.io/bash) -t 0cb88889-4e4c-4202-8626-7e397946891e

after_failure:
   - bash <(curl -s https://codecov.io/bash) -t 0cb88889-4e4c-4202-8626-7e397946891e
