language: python
python:
  - 3.7
os:
- linux  
before_install:
  - sudo apt-get install libgdal-dev
  - sudo apt-get install python3-gdal
  
install:
  - sudo apt-get -y install libproj-dev binutils gdal-bin libgdal-dev
  - pip install gdal==3.0.3 --global-option=build_ext --global-option="-I/usr/include/gdal/"
  - pip install -r requirements.txt

script:
  - python run_cwatm.py
  
after_script:
   - bash <(curl -s https://codecov.io/bash) -t 0cb88889-4e4c-4202-8626-7e397946891e

after_failure:
   - bash <(curl -s https://codecov.io/bash) -t 0cb88889-4e4c-4202-8626-7e397946891e
