language: python
python:
  - 3.7
os:
- linux  

addons:
  apt:
    packages:
    - libgdal-dev
  
before_install:
  - python -m pip install wheel
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH
  - export GDAL_DATA=$GDALINST/gdal-$GDALVERSION/share/gdal
  - export PROJ_LIB=$GDALINST/gdal-$GDALVERSION/share/proj

install:
  - pip install GDAL==$(gdal-config --version)
  - pip wheel -r requirements.txt  
  - pip install -r requirements.txt

script:
  - python run_cwatm.py
  
after_script:
   - bash <(curl -s https://codecov.io/bash) -t 0cb88889-4e4c-4202-8626-7e397946891e
